// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace VacationManager.DomainServices.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetMaxLengthToStringFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetMaxLengthToStringFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201808041211171_SetMaxLengthToStringFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
